### PR TITLE
Make test compile

### PR DESCRIPTION
**Pull request by alpe**
Minor changes in test code to make them compile and green.
`data_store_test:TestReadOffsets` is deactivated as it is constantly failing with deadlocks. I don't think the test setup is correct. Please correct me if I'm wrong but I couldn't find anything writing to the store for the test.

### CODE REVIEW

**Comment by alpe** [comment]
Still some data races left to fix. Will do a new PR.

**Comment by chrislusf** [comment]
Thanks! I applied your PR and removed the outdated test.

**Comment by chrislusf** [comment]
Do you have any idea how to fix for the "go test -race"?

**Comment by alpe** [comment]
I haven't looked into the details, yet but I hope I can find some time soon.

**Comment by alpe** [comment]
@chrislusf I've had a quick look and already identified some shared resources. I did some patches in my https://github.com/alpe/glow/tree/race_conditions branch. Please don't merge/ copy them yet. I'd like to finish a proper PR. :-)
I've started using simple sync locks. If some of the code is more performance critical we may do benchmarks and use better algorithms.

**Pull request closed without merging**
